//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/dm_snow.html
gfx/env/snowbk.tga
gfx/env/snowdn.tga
gfx/env/snowft.tga
gfx/env/snowlf.tga
gfx/env/snowrt.tga
gfx/env/snowup.tga
models/player/guerilla/guerilla.mdl
maps/dm_snow.bsp
maps/dm_snow.txt
