//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/leggo2.html
gfx/env/spacebk.tga
gfx/env/spacedn.tga
gfx/env/spaceft.tga
gfx/env/spacelf.tga
gfx/env/spacert.tga
gfx/env/spaceup.tga
maps/leggo2.bsp
